### ISSUE TITLE
Gradle 7.4.2

### ISSUE THREAD

**Issue by kelemen** [gradle-plugins/gradle-api#1]
There are no gradle-api artifacts for Gradle version 7.4.2. Is there a new (hopefully official) group/artifactId somewhere in Maven Central to provide the same binaries?

**Comment by lacasseio** [comment]
Thanks for the issue, and sorry for the late reply. The version unfortunately lagged a bit behind the official one but it was released: https://search.maven.org/artifact/dev.gradleplugins/gradle-api/7.4.2/jar

I will try to release them quickly for 2023 :-)
