### ISSUE TITLE
Gradle 8.1.1 and 8.2 missing from Maven Central

### ISSUE THREAD

**Issue by rpalcolea** [gradle-plugins/gradle-api#2]
Hi @lacasseio ,

Wondering if it would be possible to get 8.1.1 and 8.2 distributions published to Maven Central? :) 

Thanks in advance for looking at this

**Comment by lacasseio** [comment]
Thanks for the ping. I was sure I at least did the 8.1.1 but you are right I can't see it on Maven Central. I will get on this. Here are the actions for this issue (note I added the 7.6.2 release as well):

- [x] Release 8.1.1 and update runtime compatibility
- [x] Release 8.2 and update runtime compatibility
- [ ] Release 7.6.2 and update runtime compatibility
- [x] Release new toolbox version to reflect runtime compatibility

**Comment by rpalcolea** [comment]
awesome! I'll keep an eye on this :) thank you very much!

**Comment by lacasseio** [comment]
Both 8.1.1 and 8.2 have been released. Allow some time to appear in Maven Central.

**Comment by rpalcolea** [comment]
I see them now! thanks for the quick turnaround!

**Comment by lacasseio** [comment]
This was done recently.
